name: Playwright Tests

on:
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install Playwright Chromium only
        run: npx playwright install --with-deps chromium

      - name: Create users.json from secrets
        run: |
          mkdir -p data
          echo '{
            "standard_user": {
              "username": "${{ secrets.STANDARD_USER }}",
              "password": "${{ secrets.SECRET_SAUCE }}"
            }
          }' > data/users.json

      - name: Run Playwright tests
        run: npx playwright test --reporter=list,html

      - name: Upload Playwright report as artifact (.zip)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Deploy Playwright report to GitHub Pages
        if: always()
        run: |
          if [ ! -d "playwright-report" ]; then
            echo "No report folder, skipping deploy"; exit 0; fi
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git fetch
          git worktree add gh-pages
          cp -r playwright-report/* gh-pages/
          touch gh-pages/.nojekyll
          cd gh-pages
          git add .
          git commit -m "deploy: playwright report" || true
          git push --force origin HEAD:gh-pages
